name: Release

on:
    push:
        branches:
            - main
            - master
        paths-ignore:
            - 'README.md'
            - 'docs/**'
            - '.gitignore'
            - 'LICENSE'
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Release type (patch, minor, major)'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            issues: write
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Install Node.js dependencies
              run: pnpm install --frozen-lockfile

            - name: Install Python dependencies
              run: pip install -r requirements.txt

            - name: Run tests (if available)
              run: |
                  if [ -f "package.json" ] && grep -q '"test"' package.json; then
                    pnpm test
                  else
                    echo "No tests found, skipping..."
                  fi

            - name: Build plugin
              run: pnpm run build

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release

    build-and-package:
        needs: release
        runs-on: ubuntu-latest
        if: success()

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Install dependencies
              run: |
                  pnpm install --frozen-lockfile
                  pip install -r requirements.txt

            - name: Build plugin
              run: pnpm run build

            - name: Get version from package.json
              id: get_version
              run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

            - name: Create release package
              run: |
                  mkdir -p release

                  # Copy essential files
                  cp -r dist/* release/ 2>/dev/null || echo "No dist directory found"
                  cp -r frontend release/ 2>/dev/null || echo "No frontend directory"
                  cp -r webkit release/ 2>/dev/null || echo "No webkit directory"
                  cp -r backend release/ 2>/dev/null || echo "No backend directory"
                  cp -r styles release/ 2>/dev/null || echo "No styles directory"

                  # Copy configuration files
                  cp package.json release/
                  cp plugin.json release/
                  cp requirements.txt release/
                  cp README.md release/
                  cp LICENSE release/ 2>/dev/null || echo "No LICENSE file"

                  # Create zip package
                  cd release
                  zip -r "../csstats-extension-v${{ steps.get_version.outputs.version }}.zip" .
                  cd ..

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./csstats-extension-v${{ steps.get_version.outputs.version }}.zip
                  asset_name: csstats-extension-v${{ steps.get_version.outputs.version }}.zip
                  asset_content_type: application/zip
